/**
 * ============================================================================
 * EXPORT BUTTON COMPONENT - src/components/ui/buttons/export-button.js
 * ============================================================================
 * Komponen tombol untuk mengekspor laporan keuangan dalam format PDF.
 * Menggunakan library jsPDF untuk membuat file PDF langsung di browser user.
 * 
 * Fitur PDF yang dihasilkan:
 * 1. Header: Judul "LAPORAN KEUANGAN FLASHPARK" + info periode + tanggal cetak
 * 2. Tabel ringkasan: Pendapatan hari ini, bulan ini, total transaksi
 * 3. Tabel detail: Pendapatan per hari (7 hari terakhir / custom range)
 * 4. Footer: Auto-generated by FlashPark System
 * 
 * @module ExportButton
 * @path /dashboard/owner (tombol di header)
 * ============================================================================
 */

// "use client" = komponen ini berjalan di browser (butuh interaksi user: klik tombol)
"use client";

// import jsPDF = library untuk membuat file PDF dari JavaScript
import jsPDF from "jspdf";

// import autoTable = plugin jsPDF untuk membuat tabel secara otomatis
import autoTable from "jspdf-autotable";

// import useSearchParams = hook Next.js untuk membaca parameter URL (?startDate=...&endDate=...)
import { useSearchParams } from "next/navigation";

/**
 * ExportButton - Tombol Download Laporan PDF
 * 
 * @param {Object} props - Properties komponen
 * @param {Object} props.stats - Data statistik (today, month, totalTransactions)
 * @param {Array} props.chartData - Data grafik pendapatan harian [{date, revenue}]
 * @returns {JSX.Element} - Tombol hijau "Download Laporan PDF"
 */
export default function ExportButton({ stats, chartData }) {
    // baca parameter tanggal dari URL (kalau user sudah filter)
    const searchParams = useSearchParams();
    const startDate = searchParams.get("startDate");  // tanggal mulai filter
    const endDate = searchParams.get("endDate");      // tanggal selesai filter

    /**
     * handleExport - Fungsi untuk generate dan download file PDF
     * Dipanggil saat user klik tombol "Download Laporan PDF"
     */
    const handleExport = () => {
        // buat document PDF baru (default: A4 portrait)
        const doc = new jsPDF();

        // ===== 1. HEADER LAPORAN =====
        doc.setFontSize(18);   // ukuran font judul
        doc.text("LAPORAN KEUANGAN FLASHPARK", 14, 20);  // teks di posisi x=14, y=20

        doc.setFontSize(10);        // ukuran font info
        doc.setTextColor(100);      // warna abu-abu
        // tampilkan periode laporan (custom range atau "Hari Ini")
        doc.text(`Periode: ${startDate && endDate ? `${startDate} s/d ${endDate}` : 'Hari Ini'}`, 14, 28);
        // tampilkan tanggal cetak
        doc.text(`Tanggal Cetak: ${new Date().toLocaleString('id-ID')}`, 14, 33);
        // tampilkan info pencetak
        doc.text("Dicetak Oleh: Pemilik", 14, 38);

        // ===== 2. TABEL RINGKASAN STATISTIK =====
        // data ringkasan dalam format array 2D (baris x kolom)
        const summaryData = [
            [startDate && endDate ? "Total Pendapatan (Periode)" : "Pendapatan Hari Ini", `Rp ${stats.today.toLocaleString()}`],
            ["Pendapatan Bulan Ini", `Rp ${stats.month.toLocaleString()}`],
            ["Total Transaksi", `${stats.totalTransactions} Kendaraan`]
        ];

        // render tabel ringkasan ke PDF
        autoTable(doc, {
            startY: 45,                                    // posisi Y mulai tabel
            head: [['Metrik', 'Nilai']],                   // header kolom
            body: summaryData,                             // isi tabel
            theme: 'grid',                                 // style tabel dengan garis
            headStyles: { fillColor: [32, 77, 210] },      // warna header: biru FlashPark (RGB)
        });

        // ===== 3. TABEL DETAIL PENDAPATAN HARIAN =====
        // judul section detail
        doc.text(`Rincian Pendapatan ${startDate && endDate ? 'Per Hari' : '7 Hari Terakhir'}:`, 14, doc.lastAutoTable.finalY + 15);

        // konversi data chart ke format tabel 2D
        const detailData = chartData.map(item => [
            item.date,                                     // kolom tanggal
            `Rp ${item.revenue.toLocaleString()}`          // kolom pendapatan (format Rupiah)
        ]);

        // render tabel detail ke PDF
        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 20,         // mulai setelah tabel sebelumnya
            head: [['Tanggal', 'Pendapatan']],             // header kolom
            body: detailData,                              // isi tabel
            theme: 'striped',                              // style tabel bergaris-garis
        });

        // ===== 4. FOOTER =====
        const finalY = doc.lastAutoTable.finalY + 20;      // posisi setelah tabel terakhir
        doc.setFontSize(10);
        doc.text("Auto-generated by FlashPark System", 14, finalY);

        // ===== 5. DOWNLOAD FILE PDF =====
        // save = trigger download file PDF ke komputer user
        // nama file: Laporan_Keuangan_2024-01-15.pdf (tanggal hari ini)
        doc.save(`Laporan_Keuangan_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    return (
        // tombol hijau "Download Laporan PDF"
        <button
            onClick={handleExport}    // saat diklik, jalankan handleExport
            style={{
                backgroundColor: '#10B981',   // warna hijau (emerald)
                color: 'white',               // teks putih
                border: 'none',               // tanpa border
                padding: '10px 20px',         // padding dalam
                borderRadius: '8px',          // sudut bulat
                fontWeight: '600',            // teks tebal
                cursor: 'pointer',            // cursor tangan
                display: 'flex',              // flexbox untuk ikon + teks
                alignItems: 'center',         // center vertikal
                gap: '8px'                    // jarak ikon ke teks
            }}
        >
            {/* ikon download + label teks */}
            <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}><img src="/content/download-pdf.svg" alt="download" style={{ width: '18px', height: '18px' }} /> Download Laporan PDF</span>
        </button>
    );
}
