"use client";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSearchParams } from "next/navigation";

export default function ExportButton({ stats, chartData }) {
    const searchParams = useSearchParams();
    const startDate = searchParams.get("startDate");
    const endDate = searchParams.get("endDate");

    const handleExport = () => {
        const doc = new jsPDF();

        // 1. Header Laporan
        doc.setFontSize(18);
        doc.text("LAPORAN KEUANGAN FLASHPARK", 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Periode: ${startDate && endDate ? `${startDate} s/d ${endDate}` : 'Hari Ini'}`, 14, 28);
        doc.text(`Tanggal Cetak: ${new Date().toLocaleString('id-ID')}`, 14, 33);
        doc.text("Dicetak Oleh: Owner", 14, 38);

        // 2. Ringkasan Statistik
        const summaryData = [
            [startDate && endDate ? "Total Pendapatan (Periode)" : "Pendapatan Hari Ini", `Rp ${stats.today.toLocaleString()}`],
            ["Pendapatan Bulan Ini", `Rp ${stats.month.toLocaleString()}`],
            ["Total Transaksi", `${stats.totalTransactions} Kendaraan`]
        ];

        autoTable(doc, {
            startY: 45,
            head: [['Metric', 'Nilai']],
            body: summaryData,
            theme: 'grid',
            headStyles: { fillColor: [32, 77, 210] }, // Biru Flashpark
        });

        // 3. Detail Data Harian (dari Chart Data)
        doc.text(`Rincian Pendapatan ${startDate && endDate ? 'Per Hari' : '7 Hari Terakhir'}:`, 14, doc.lastAutoTable.finalY + 15);

        const detailData = chartData.map(item => [
            item.date,
            `Rp ${item.revenue.toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 20,
            head: [['Tanggal', 'Pendapatan']],
            body: detailData,
            theme: 'striped',
        });

        // 4. Footer
        const finalY = doc.lastAutoTable.finalY + 20;
        doc.setFontSize(10);
        doc.text("Auto-generated by FlashPark System", 14, finalY);

        // Save PDF
        doc.save(`Laporan_Keuangan_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    return (
        <button
            onClick={handleExport}
            style={{
                backgroundColor: '#10B981',
                color: 'white',
                border: 'none',
                padding: '10px 20px',
                borderRadius: '8px',
                fontWeight: '600',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '8px'
            }}
        >
            <span>📄 Download Laporan PDF</span>
        </button>
    );
}
